51 -  enchance loading bars component with additional (optional) text below icon
danieljancar/chorizo pull request #71
Opened 2024-03-06 14:21 UTC by MRX1621

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** and other relevant documents.

## Description

fix(course): implement "Is loading..." - Message and place loading-icon in centre

## Screenshots (if appropriate):
![image](https://github.com/danieljancar/chorizo/assets/78649308/9609ca69-0a5f-4f74-91a5-653c5640b6b4)

2024-03-06 15:00 UTC, danieljancar requested changes
I only want the changes in the `loading-bars` component and not the loading component being imported and used in the `agenda` and `home` components, which you probably used to test your loading additions.

2024-03-06 15:05 UTC, danieljancar requested changes

2024-03-06 15:05 UTC, danieljancar commented on apps/course/src/app/shared/feedback/loading-bars/loading-bars.component.html
> +  <!-- Optionaler Lade-Text -->
Overkill and german comment. Please remove 🦖

2024-03-06 15:05 UTC, danieljancar commented on apps/course/src/app/shared/feedback/loading-bars/loading-bars.component.ts
> +  @Input() loadingText: string = '';
Please use type:
```ts
@Input() loadingText: string | null;
```
And in the template check if `loadingText` has a string value:
```html
@if (loadingText) {
  <p>{{ loadingText }}</p>
} 
```
Also there's no need for the `class="loading-text"` in the html tag.

2024-03-06 15:05 UTC, danieljancar commented on apps/course/src/app/features/course/agenda/course-agenda.component.html
> +  <h1>Content is loading... Don't worry</h1>
Please remove all this.

2024-03-06 15:05 UTC, danieljancar commented on apps/course/src/app/features/course/agenda/course-agenda.component.ts
> +  imports: [LoadingBarsComponent],
Remove

2024-03-07 07:04 UTC, MRX1621 commented
is changed

2024-03-07 07:43 UTC, danieljancar requested changes

2024-03-07 07:43 UTC, danieljancar commented on apps/course/src/app/features/course/agenda/course-agenda.component.ts
> +  imports: [LoadingBarsComponent],
Still needs to be removed as it's not used yet in this component.

2024-03-07 07:43 UTC, danieljancar commented on apps/course/src/app/shared/feedback/loading-bars/loading-bars.component.ts
> +  shouldShowLoadingText(): boolean {
This method can be removed as it's not used anymore.

2024-03-07 08:11 UTC, MRX1621 commented
V3: changed (again)

2024-03-07 08:39 UTC, danieljancar approved these changes
Looks good.

2024-03-07 10:04 UTC, merged